[tools]
# from core https://mise.jdx.dev/core-tools.html
java = "temurin-25.0.1+8.0.LTS"
node = "latest"
deno = "latest"
bun = "latest"

# from registry https://mise.jdx.dev/registry.html
atuin = "latest"
biome = "latest"
claude = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
ghq = "latest"
github-cli = "latest"
jq = "latest"
ni = "latest"
opencode = "latest"
pnpm = "latest"
ripgrep = "latest"
tbls = "latest"
trivy = "latest"
yq = "latest"

# from backends https://mise.jdx.dev/dev-tools/backends/
"aqua:koki-develop/gat" = "latest"
"aqua:stateful/runme" = "latest"
"aqua:k1LoW/runn" = "latest"
"npm:npm-check-updates" = "latest"
