[tools]
# from core https://mise.jdx.dev/core-tools.html
java = "temurin-25.0.1+8.0.LTS"
node = "latest"
deno = "latest"
bun = "latest"

# from registry https://mise.jdx.dev/registry.html
atuin = "latest"
biome = "latest"
cloudflared = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
jq = "latest"
ni = "latest"
opencode = "latest"
pnpm = "latest"
ripgrep = "latest"
starship = "latest"
tbls = "latest"
trivy = "latest"
yq = "latest"

# from backends https://mise.jdx.dev/dev-tools/backends/
"github:k1LoW/runn" = "latest"
"github:k1LoW/git-wt" = "latest"
"github:koki-develop/gat" = "latest"
"github:stateful/runme" = "latest"
